### ISSUE TITLE
Quickest way to go from .argdown file to a Viz.JS map published to a web-page

### ISSUE THREAD

**Issue by antonostrovsky** [christianvoigt/argdown#147]
I would like to embed an Argdown Viz.js map into my static HTML website.
Ideally it should look like what is on https://argdown.org/ page:
![image](https://user-images.githubusercontent.com/62160100/78616181-6e903600-786b-11ea-8b3f-2fc9848f76d2.png)

What is the easiest way to get that result?

Thank you!

**Comment by christianvoigt** [comment]
funny that you should ask, because that is exactly what I am currently working on. Last week I wrote a web component that looks exactly like the Vue-Component on argdown.org. Currently I am working on a Markdown-It plugin, so that Argdown code fences in Markdown are automatically converted into instances of the web component. This will mean that you can now combine Markdown and Argdown which will open up many new possibilities (for example for creating Argdown presentations).

I still have to test it and write a documentation for it, but I think probably at the end of next week we will have a very nice workflow for this. Until then, you can copy and paste the generated svg or use a png, so you will not have the "pan & zoom" features of the web component.

**Comment by antonostrovsky** [comment]
Thank you for this, Christian! I would be delighted to test the new functionality when it is ready and try hosting it on GitHub pages.

**Comment by antonostrovsky** [comment]
@christianvoigt , is the "web component that looks exactly like the Vue-Component on argdown.org" that you mentioned available for testing? I'd like to try integrating it into my website.

Thank you in advance

**Comment by christianvoigt** [comment]
I'm still on it. This took a week longer as expected. The original Viz.js library has been "archived" for some time and I am switching to a new fork (https://github.com/aduh95/viz.js). It took last week to get this fork working for our use case (the author was very helpful and added the feature we needed), but now I can finish my work on this and it is really great that Argdown is based on a new version of Viz.js that will be maintained in the future. I will get back to you here if you can test the new web component.

**Comment by christianvoigt** [comment]
Hi @antonostrovsky,
I finally released everything (@argdown/cli, argdown-vscode, sandbox, docs ...).  I had some webpack-related configuration problems that took me another week to fix, but now the whole workflow should be straightforward. Take a look at:

- The [Changelog](https://argdown.org/changes/) for an overview
- the new guide [Using Argdown in Markdown](https://argdown.org/guide/using-argdown-in-markdown.html) 
- the new guide [Embedding your Argdown maps in a webpage](https://argdown.org/guide/embedding-your-maps-in-a-webpage.html)

If these leaves any questions open on how to use the new features, just ask them here.

The web component is now also used in the documentation, so it has already been tested extensively. But getting feedback from you would still be helpful. If you run into any problems, please create a new issue on Github.
