### ISSUE TITLE
Argumente ohne Titel nicht möglich

### ISSUE THREAD

**Issue by lilysabath** [christianvoigt/argdown#16]
Wenn Argumente keinen Namen haben, wird ihnen in der Map die Überschrift "Untitled" gegeben. 
Außerdem differenzieren sie sich dann farblich nicht mehr von den Statements.
Ich fände es schöner, wenn man Argumente ganz ohne Überschrift haben kann, die dann trotzdem die gleiche Farbe haben wie die restlichen Argumente.

**Comment by christianvoigt** [comment]
I am not sure I understand this correctly. What do you mean by "arguments without names"? Do you mean an argument reconstruction without a name? 

But argument reconstructions without titles *are* visualized differently than statements in the map view. Apart from this case there can not be any arguments without titles, because any line of text without a title is interpreted as a statement.

What we could do is add a feature for the dot export: statements without a title should (optionally) be visualized by omitting the automatically generated title ("Untitled x") and only showing the statement text.

If I misunderstood your request, please clarify what you meant.

**Comment by lilysabath** [comment]
I did mean arguments (not argument reconstructions) without titles, but as you explained those are not possible. 
But I still think it would be good to add the feature you proposed, so that there is an option to show statement texts without any titles.

**Comment by christianvoigt** [comment]
I've added statementTitleMode and argumentTitleMode settings to the DOT export. By default the automatically generated titles of untitled nodes are hidden.

```
statementTitleMode: hide-untitled | title | text
argumentTitleMode: hide-untitled | title | description
```
