### ISSUE TITLE
argdown-cli  - argdown markdown

### ISSUE THREAD

**Issue by antonostrovsky** [christianvoigt/argdown#164]
Hello!

When I am converting a markdown-argdown document to HTML, is there any way to add the following to the beggining of my *.md document, and then get it in exactly the same form without having it transformed?

```
---
layout: post
---
```

The above is a so-called Jekyll liquid that would help me automatically render the resulting HTML page as a post.

Thank you!

**Comment by christianvoigt** [comment]
`@argdown/cli` currently uses [markdown-it](https://github.com/markdown-it/markdown-it) under the hood as the Markdown parser, together with `@argdown/markdown-it-plugin`. For all questions regarding the features of the Markdown parser, please refer to the Markdown-It docs.

If you want to configure the Markdown parser or extend it with plugins, I strongly recommend to install one of the three Markdown parsers for which I have written an Argdown plugin and use them directly instead of using `@argdown/cli`. I have written some instructions about how to add the plugins to the parsers, but if you run into any problems, I can help you with it.

Jekyll is a static site generator that is written in Ruby and uses different Markdown parsers (written in Ruby, not in Javascript). So I am not sure that you can achieve what you want. I would probably recommend to use a static site generator written in Node.js (like Gatsby) so that you can make use of the Argdown plugins.

It would be helpful if you tell me more about your use case.

**Comment by tonysepia** [comment]
Thank you for taking the time to respond in detail, Christian.

I am simply trying to build a workflow for documenting arguments in books I read.
One feature that I liked was that I could (in theory) write something in markdown-argdown, export the data, commit changes to Github and the site would be automatically generated for Github pages.
Jekyll is built into Github pages, so that's why I have been guided in that direction.

I keep having problems with debugging Jekyll, and if I get a few more I will finally move to Gatsby and will simply export pages to /docs subfolder, which will be the Github Pages root.

For now, I will try to ask the question on the markdown-it project repo and will see where the process takes me :)

**Comment by christianvoigt** [comment]
If the three lines before the exported html are really all you need, you could simply write a script (in node.js or shell) that adds those to your exported files and run it after using `argdown markdown`.

**Comment by antonostrovsky** [comment]
@christianvoigt Thank you, the above is a good way to solve the problem!
