### ISSUE TITLE
Examples broken on syntax documentation page?

### ISSUE THREAD

**Issue by DawnPaladin** [christianvoigt/argdown#206]
Hello! Your [syntax documentation page](https://argdown.org/syntax/#statements) has a bunch of empty boxes, e.g. on the left side of the table that says "A paragraph with text is called a 'statement'..." When I use Inspect Element on these areas, it looks like there's supposed to be an Argdown map in there, but nothing's showing up. I'm guessing it's broken?

I'm using Firefox on MacOS, but I checked it in Safari and Chrome too.

**Comment by christianvoigt** [comment]
Thanks, I did not know that. I will try to find time to fix this in the next week.

**Comment by christianvoigt** [comment]
This is strange. The examples disappear if you directly jump to an anchor (e.g. "#statements"). If you open the index page (argdown.org) go to the syntax page and scroll to the examples, everything is fine.

**Comment by christianvoigt** [comment]
ok, I fixed it. 

For documentation, here is what was causing this: This was some weird browser behaviour. If the browser loads a url with an anchor, the "initial-view" property of the argdown-map web component is first undefined even if explicitely set to "source" and only later changes to "source" (I don't know why). The web component did not expect this property to change and so thought it had to create an empty map view (instead of the source view).

I changed the web component so that it will create and activate the appropriate views if the "initial-view" property changes.

I will also publish a new version of the web component (and all the packages that depend on it).
