### ISSUE TITLE
sandbox gets a 404 error

### ISSUE THREAD

**Issue by zoechow** [christianvoigt/argdown#208]
https://argdown.org/ has lots of links to an online sandbox, at https://argdown.org/sandbox/. But this link gives a 404 error

**Comment by christianvoigt** [comment]
Thanks, I updated the docs this week because of issue #206. Somehow the sandbox was not correctly built/uploaded. I repeated the process and the sandbox is online again. It is so great to see that there are Argdown users like you now that instantly find these issues and post them here.

Note to myself: If I have the time I should really try to automate the whole build process with Github actions.
