### ISSUE TITLE
Problems with square and angle brackets

### ISSUE THREAD

**Issue by lilysabath** [christianvoigt/argdown#22]
In argument and statement texts, round brackets work, but square and angle brackets don't.
![bildschirmfoto 2017-05-03 um 13 50 50](https://cloud.githubusercontent.com/assets/27997967/25659411/f1b51906-3007-11e7-8d6e-018de0756a49.png)
As shown in this example, if I put text in square brackets, only the first bracket will show up in the map.
Angle brackets, or even single greater- or smaller-than signs don't show up in the map at all.
Also, any line of text in square or angle brackets will automatically be displayed in the same colors used for the statements or arguments.

**Comment by lilysabath** [comment]
Correction: single greater-than or smaller-than signs do show up in the map if they are not (like in the example) preceded by a line of text in angle brackets. With angle brackets themselves there is the same problem as with the square brackets.

**Comment by lilysabath** [comment]
I can't reproduce the example above anymore, because now there is neither a Map nor HTML shown when I use square or angle brackets.
Neither this `[Statement]: Statement 
  +<Argument>: <Text>`
nor this `[Statement]: Statement 
  +<Argument>: [Text]` works.

**Comment by christianvoigt** [comment]
This is not a bug. Text in square brackets is always interpreted as reference to a statement. Text in angle brackets is always interpreted as reference to an argument. References to arguments or statements can not be used as part of a statement's content. Doing so will lead the parser to throw an error.

Instead, you currently have to use "mentions" like this: 

```
[Statement]: Content
  + <Argument>: @<Another argument>

[Statement]: Content
  + <Argument>: @[Another statement]
````
To allow angle and square brackets in statements, we need to escape the characters by using "html entities". This already works out of the box if we export the data to html. And because the DOT export also uses html labels, it works there as well. Here is an example:

````
[Statement]: Statement 
  + <Argument>: &#91;Text&#93;
````
