### ISSUE TITLE
Klammern in inference pattern

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#23]
```
<Arg>

  (1) P1
  (2) P2
  --aus (1)--
  (3) C
```
wirft einen Fehler; ohne Klammern
```
<Arg>

  (1) P1
  (2) P2
  --aus 1--
  (3) C
```
ist aber alles OK

**Comment by christianvoigt** [comment]
The supported syntax for inference pattern currently looks like this:

```
(1) A
(2) B
-- 
Inference Pattern 1, Inference Pattern 2 (metadata 1: text; metadata 2: 1,2,3; metadata 3: 1) 
--
(3) C
```

You can also define the whole inference in one line as you did.

The syntax highlighting for inferences currently simply looks for the starting and ending --. Everything inside is highlighted as belonging to the inference definition. This is simple and fast. I think this is another case for a linter error instead of a more sophisticated syntax highlighting.
