### ISSUE TITLE
Add support for github.dev for the VSCode Extension

### ISSUE THREAD

**Issue by Coda-Coda** [christianvoigt/argdown#298]
I am not sure if it would be possible, but if it is, it would be really great to have support for https://github.dev for the Argdown VSCode extension. This would make it very simple for any user with a web-browser to edit Argdown files in any GitHub repo simply by pressing `.` on the GitHub page with the Argdown files and adding the Argdown extension.

Currently, attempting to install the Argdown extension from https://github.dev/christianvoigt/argdown/tree/master/examples gives the error  "The 'Argdown' extension is not available in Visual Studio Code for the Web."

See also: https://code.visualstudio.com/docs/editor/vscode-web#_extensions

**Comment by christianvoigt** [comment]
Hi, I am currently working on this. Maybe some features will be missing in the web version, but I think most features will work.

**Comment by Coda-Coda** [comment]
Awesome!

**Comment by christianvoigt** [comment]
It took some time, but with v1.8.1 the argdown-vscode extension does run on vscode.dev and github.dev. At the moment the export features have been deactivated, because they use @argdown/language-server. Language servers currently do not support [virtual workspaces](https://github.com/microsoft/language-server-protocol/issues/1264).

**Comment by Coda-Coda** [comment]
Nice!! This opens up some neat opportunities for more convenient collaboration on Argdown diagrams - thanks @christianvoigt!!
