### ISSUE TITLE
VSCode preview broken for Argdown extension 1.8.1

### ISSUE THREAD

**Issue by v3P3u** [christianvoigt/argdown#313]
See pictures.

![image](https://user-images.githubusercontent.com/58634304/151712220-b2ca5de7-197c-4a7e-9613-21623082a168.png)
Argdown VSCode extension 1.8.0. Preview works fine. 

![image](https://user-images.githubusercontent.com/58634304/151712255-9ed0d99a-624f-4260-8bee-0fcd4fdef865.png)
Argdown VSCode extension 1.8.1. The button tree is broken. For graphs, the preview area is limited.

**Comment by christianvoigt** [comment]
Thanks for the report. v1.8.1 was the fix for the same issue in the browser (vscode.dev). I changed the resource paths for css and image files in the preview. The new paths do apparently not work in the desktop-version. I will try to fix it at the end of next week.

**Comment by christianvoigt** [comment]
Just released 1.8.2 which should fix it. I am currently quite busy (started a new job) so it took me a while to find the time to do this. While I was at it I used the opportunity to update the whole codebase of the Argdown preview to reflect the changes in the official Markdown preview. This was a long overdue step and will pay off in the long run.

If you notice any new issues because of this, please post a new issue.
