### ISSUE TITLE
brackets used in inference rules are throwing parser errors

### ISSUE THREAD

**Issue by xylomorph** [christianvoigt/argdown#40]
Though the following is fine

```
<arg-title>: descr

(1) premise 
--
Some inference rule (Some additional info: 1,2)
--
(4) conclusion
```

the next two examples are throwing parser errors

```
<arg-title>: descr

(1) premise 
--
Some inference rule (Some additional info: 1,2) some more
--
(4) conclusion
```

```
<arg-title>: descr

(1) premise 
--
Some inference (more) rule (Some additional info: 1,2)
--
(4) conclusion
```

**Comment by christianvoigt** [comment]
My comment from #39 applies here as well. The second and third examples are not valid Argdown, according to the syntax rules for inferences. How should these examples even be parsed?

**Comment by xylomorph** [comment]
I even didn't know that there are syntax rules for inferences :) From the user point of view, I would prefer to allow every string, since a lot can come to mind to describe the inference rule (e.g. *"modus ponens (applied to 1,2) & conj.intr. (with 3, 4)"*). In case the string allows for a formalization by complying special syntax rule (e.g. to check validity automatically) the better. However, strings not meeting these constraints, should then perhaps not parsed further.

**Comment by christianvoigt** [comment]
Argdown's purpose is not only to be easily readible for humans, but for computers as well. In this case the syntax rules allow the computer to understand that there is a list of inference rules and optionally a list of metadata for these inference rules (allowing you to state which statements where used for example). So these are not simply some arbitrary rules restricting the user's freedom. Imagine for example a plugin for Argdown that allows you to query for applications of an inference rule in all reconstructions. 

Also, the current format is already more flexible than you might think. You could for example write the following:

`modus ponens, conj.intr. (applied-to: 1,2,3,4; something-else: blablabla)`

You can add any metadata fields you like, including lists of metadata values. Or you can omit the metadata completely.

What your example shows me is that it might be a good idea to change the format so that metadata is not attached to the inference step as a whole, but instead to applications of inference rules within this inferential step. This would result in the following format:

`inference rule (metadata: blabla), inference rule 2 (metadata: 1,2,3)`

What do you think, @ggbetz?

**Comment by ggbetz** [comment]
I think the current syntax is fine. However, I tend to agree with @xylomorph in saying that the parser should be as error-tolerant as possible. E.g., it should try to parse an inference pattern; but if the inference pattern fails to obey a certain pattern and contains, for example, more than just one pair of brackets, the entire string should treated as inference pattern and the document should be parsed.

I think this idea can be generalized: There should be fall-back options for different entities which allow for parsing documents that contain syntax errors.

**Comment by christianvoigt** [comment]
@ggbetz: Don't you think inference-rule specific metadata would be an improvement (especially regarding information about sentences used).

Regarding your general point about fall-back options: While this may be nice from a UX point of view, this is currently not my development priority as it would make the parser code much more complicated and harder to maintain. As I said, the aim of Argdown is not only to make users happy, but also to avoid headaches for programmers, by defining syntax rules that are easy to learn, but also easy to parse.

Currently my priority is to communicate these actually quite simple rules clearly to the user with the help of tutorials and documentation, and build a linter that provides clear feedback of what is wrong with your code and how you can fix it. The linter code may open up ways of error recovery strategies, but I think right now it is too early to focus on that. 

Some more technical background: You have to keep in mind that the Argdown parser is not a combination of small Regex-based parsers that work independently of each other (for example one parser for inferences, one for statement references and so on) so that one parser might sucessfully run while others fail. Instead it is a top down LL(k) parser, that recursively tries to apply syntax rules to the lexed tokens. If it has not parsed all tokens and cannot find anymore rules to apply, it will simply stop parsing and produce an error. Error recovery will not work out of the box, but has to be added explicitely to the language definition.

**Comment by ggbetz** [comment]
Yes, I think inference-rule specific metadata is useful. But I thought that is what the brackets are for. To me, its currently not clear whether Argdown should prescribe the structure of data in the brackets, or whether users can do so, depending how they process the argdown file. 


> Am 25.11.2017 um 17:17 schrieb Christian Voigt <notifications@github.com>:
> 
> @ggbetz: Don't you think inference-rule specific metadata would be an improvement (especially regarding information about sentences used).
> 
> Regarding your general point about fall-back options: While this may be nice from a UX point of view, this is currently not my development priority as it would make the parser code much more complicated and harder to maintain. As I said, the aim of Argdown is not only to make users happy, but also to avoid headaches for programmers, by defining syntax rules that are easy to learn, but also easy to parse.
> 
> Currently my priority is to communicate these actually quite simple rules clearly to the user with the help of tutorials and documentation, and build a linter that provides clear feedback of what is wrong with your code and how you can fix it. The linter code may open up ways of error recovery strategies, but I think right now it is too early to focus on that.
> 
> Some more technical background: You have to keep in mind that the Argdown parser is not a combination of small Regex-based parsers that work independently of each other (for example one parser for inferences, one for statement references and so on) so that one parser might sucessfully run while others fail. Instead it is a top down LL(k) parser, that recursively tries to apply syntax rules to the lexed tokens. If it has not parsed all tokens and cannot find anymore rules to apply, it will simply stop parsing and produce an error. Error recovery will not work out of the box, but has to be added explicitely to the language definition.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Prof. Gregor Betz

Karlsruhe Institute of Technology (KIT)
Institute of Philosophy

Douglasstr. 24
Building 09.20
D-76133 Karlsruhe, Germany

Tel: +49-721-608 42149
Fax: +49-721-608 43084

http://www.philosophie.kit.edu/mitarbeiter_betz_gregor.php
http://debatelab.philosophie.kit.edu/

/KIT – The Research University in the Helmholtz Association/

**Comment by christianvoigt** [comment]
Yes, that is how the metadata will work in both cases. But the alternatives in question are the following. The current format is like this:

```
-- Modus Ponens, Modus Tollens (my-meta-data: blablabla) --
```

But I think it would probably be better to switch to the following format (which was what Basti was trying to  do):

```
-- Modus Ponens (my-meta-data: blablup), Modus Tollens (my-meta-data: blipblap) --
```

**Comment by ggbetz** [comment]
I see. I still prefer the current format. All examples in the critical thinking course obey this format. 

Also, something like this:

> -- Modus Ponens (my-meta-data: blablup), Modus Tollens (my-meta-data: blipblap)


would only make sense if you were able to refer to implicit preliminary conclusions. So I doubt that this is very useful. ;-)


> Am 26.11.2017 um 17:25 schrieb Christian Voigt <notifications@github.com>:
> 
> Yes, that is how the metadata will work in both cases. But the alternatives in question are the following. The current format is like this:
> 
> -- Modus Ponens, Modus Tollens (my-meta-data: blablabla) --
> 
> But I think it would probably be better to switch to the following format (which was what Basti was trying to do):
> 
> -- Modus Ponens (my-meta-data: blablup), Modus Tollens (my-meta-data: blipblap)
> --
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Prof. Gregor Betz

Karlsruhe Institute of Technology (KIT)
Institute of Philosophy

Douglasstr. 24
Building 09.20
D-76133 Karlsruhe, Germany

Tel: +49-721-608 42149
Fax: +49-721-608 43084

http://www.philosophie.kit.edu/mitarbeiter_betz_gregor.php
http://debatelab.philosophie.kit.edu/

/KIT – The Research University in the Helmholtz Association/

**Comment by christianvoigt** [comment]
Right, good point regarding the implicit preliminary conclusions. @xylomorph: how do you solve this problem?

I think it is a good idea to try to think this through (though I am fine with both alternatives). So here are my thoughts so far:

Let's call the first alternative "inference based metadata" and the second "inference rule based metadata". What are possible use cases? Some useful metadata could be:

1. depends on sentences
2. applied to sentences
3. is the inference deductive/non-deductive
4. other categories for inference rules, i.e. temporal,  utilitarian or probabilistic reasoning
5. formalizations

(have I forgotten anything?)

## ad 1. 

Here we don't have the problem of implicit preliminary conclusions, right? If consecutively applied inference rules use additional premises, it makes sense to distinguish between dependencies of the different rules.

## ad 2. 

Here applies Gregor's point about implicit preliminary conclusions. I don't really see a solution for that if we go with inference rule based metadata. If we go with inference based metadata it would still be possible to add preliminary conclusions and thus differentiate between the different inference rules.

## ad 3., 4. and 5.

While the metadata in 1. and 2. describes properties of inference rule applications in arguments, 3., 4. and 5. describe properties of inference rules themselves (across all applications). So it might make more sense to later add the possibility for users to specify these properties in a general metadata section. On the other hand, many users would probably like to add formalizations directly in the argument reconstructions.

The problem with inference based metadata in case of 3. and 4. is that different inference rules may belong to different categories. But it is plausible that the following rule is true: if a set of inference rules contains a rule of a certain category x (e.g. non-deductive), the whole set can be categorized as belonging to that category.

It would still be nice to "tag" inference rules (and not only inferences) with such categories. For example a plugin could answer a question like "which inference rules of type x were used in this debate?"

**Comment by ggbetz** [comment]
Just briefly re 1: "depends on" is really an info about the conclusion that is drawn and not so much the inference rule applied. That seems to me another reason to stick with the format

```
---
inference rule 1, inference rule 2 (follows from x,y; depends on z)
---
```

Also, somebody who wants more specific info for each of the individual steps merged in the above inference can make the application of the two inference rules explicit as two inference steps in the argument. 

```
---
inference rule 1 (follows from x1,y1; depends on z)
---
...
---
inference rule 2 (follows from x2,y2; depends on z)
---
...
```

**Comment by christianvoigt** [comment]
ok, as there are no more comments from @xylomorph and I am fine with the current syntax, I will close this.
