### ISSUE TITLE
Hard to spot Error Message

### ISSUE THREAD

**Issue by cwkit** [christianvoigt/argdown#76]
After working at a relatively large Argdown File and deleting several lines, a standard error occured. However the error message was relatively hard to spot.
The Error, an additional line between two premises of an Argument, is very hard to spot, when the statement is long and the additional line below contains no blanks. In that case, the Error Message (Marked as an X) can only be seen at the end of the premise text but not at the beginning of the new line.

```
<Argument>

  (1) [Statement A]: High Amount of Text ......................................................... X

  (2) [Statement B]
```
It would be useful, if argdown could additionally mark the number of the line in which the error occurs.

**Comment by christianvoigt** [comment]
This would be difficult and is unnecessary: 

- You should see a red marker on the right side of the document showing you the location of the error.
- Alternatively you can open the "problems view" which will also show you all current problems in your document. Double clicking on a problem will lead you to the line of the error.
- You can also "Toggle Word Wrap" so that your longer lines of text are wrapped.
