### ISSUE TITLE
Is a blank line between arg-title and reconstruction necessary?

### ISSUE THREAD

**Issue by xylomorph** [christianvoigt/argdown#8]
Sollte nicht vlt. das 

```
<Argument 1>
(1) First premise (this is is a normal statement 

```

genauso gehen (behandelt werden) wie

```
<Argument 1>

(1) First premise (this is is a normal statement 

```

**Comment by christianvoigt** [comment]
I don't think so. In general we use empty lines to distinguish between block elements. `<Argument 1>` works here as a heading for the argument and should work similar to other kinds of headings. 

A second reason, why we should avoid this: argument titles with and without argument descriptions should behave in the same way. But if there is a description, an empty line is needed to identify the end of the description (as the description may contain single line breaks to make it more readable).

**Comment by ggbetz** [comment]
I think it's OK as is. But we should reckon that this might be counter-intuitive to some users. So a medium-term todo would be to make sure that syntax highlighting in the editor points out that in
```<Argument>
(1) P1
(2) P2 ...
```
the premiss-conclusion is not recognised as such (and that the above code is illegal).

Maybe syntax-highlighting of premiss-conclusion reconstructions should check whether there is a blank line before the first premiss and not color the code at all if not.

**Comment by christianvoigt** [comment]
I agree, in some cases the syntax highlighting diverges from the way the syntax rules of the parser and this is counterintuitive. In part the syntax rules simply changed during development. But in part this is also due to the syntax highlighting using a much simpler parsing method that has some limitations. We should probably discuss these issues in [christianvoigt/language-argdown](https://github.com/christianvoigt/language-argdown).

Apart from that I think the rule "one empty line after each block element" is intuitive and we should avoid exemptions. As I said we need this rule to allow arbitrary line breaks in statements:

```Markdown
[Statement]: I 
am
a
statement.

Next statement.
```
