### ISSUE TITLE
Sandbox Syntax highlighting: line-break in heading

### ISSUE THREAD

**Issue by ggbetz** [christianvoigt/argdown#83]
A heading with a linebreak is not fully recognized by syntax highlighter (but parser correctly recognizes heading):
```
# This is
one heading
```

**Comment by ggbetz** [comment]
This **is** an issue in the VS Code extension, too!

**Comment by christianvoigt** [comment]
By default, Codemirror skips empty lines in its token stream so it is not possible to match them in the language mode. This behaviour can be changed with a `blankLine(state)` method in a JavaScript mode file. As this is a minor issue and would require switching from a Codemirror simple mode to a full mode, I will currently not fix this in the Sandbox.

The issue will be fixed in the VS Code tmLanguage definition in the next version.
