### ISSUE TITLE
Extension removed from vscode (due to backdoor in dependency?)

### ISSUE THREAD

**Issue by TimSoethout** [christianvoigt/argdown#98]
It seems the extension was removed from vscode. Presumably due to this: https://github.com/dominictarr/event-stream/issues/116

When scanning my machine this came up:
```
$find ~ -name "flatmap-stream"
/Users/tim/.vscode/extensions/christianvoigt.argdown-vscode-1.0.2/node_modules/flatmap-stream
```

**Comment by christianvoigt** [comment]
Yes, you are right, I only found out after writing to Microsoft about this. I am already working on updating the extension and hopefully it will be back online in a few hours. 

The package was automatically installed by the yeoman generator for VS Code extensions, so I did not even realized that it was used. You can read more about the issue here: https://code.visualstudio.com/blogs/2018/11/26/event-stream

**Comment by christianvoigt** [comment]
Only the VS Code extension is affected. The browser sandbox and the commandline tool do not depend on event-stream and can be used as long as the extension is offline.
